sudo: required
services:
          - docker

before_install:
          - docker build -t hemanth318/react-app -f Dockerfile.dev .

script:
          - docker run -e CI=true hemanth318/react-app npm run test

language: generic
